version: '3'
services:
  frontend:
    container_name: checlean_frontend
    build: .
    command: npm start -- --host 0.0.0.0 --disable-host-check
    tty: true
    volumes:
      - .:/app
      - data-frontend-libs:/app/node_modules
    ports:
      - 4200:4200
volumes:
  data-frontend-libs:
    driver: local
